In [4]:
import numpy as np
import pandas as pd

In [5]:
df = pd.read_csv('pima-indians-diabetes.csv', skiprows=9, header=None)
df.head()

0    1   2   3    4     5      6   7  8
0  6  148  72  35    0  33.6  0.627  50  1
1  1   85  66  29    0  26.6  0.351  31  0
2  8  183  64   0    0  23.3  0.672  32  1
3  1   89  66  23   94  28.1  0.167  21  0
4  0  137  40  35  168  43.1  2.288  33  1

In [6]:
# pima는 Numpy n-dimensional array
pima = df.values
pima.shape

(768, 9)

In [17]:
# pima[행,열]
X = pima[:,:-1]
y = pima[:,-1]

In [18]:
X.shape, y.shape

((768, 8), (768,))

In [27]:
X = df.iloc[:,:-1].values
y = df[8]          # Series
y = y.values         # Numpy array

In [40]:
df.describe()

6         148          72          35           0        33.6  \
count  767.000000  767.000000  767.000000  767.000000  767.000000  767.000000   
mean     3.842243  120.859192   69.101695   20.517601   79.903520   31.990482   
std      3.370877   31.978468   19.368155   15.954059  115.283105    7.889091   
min      0.000000    0.000000    0.000000    0.000000    0.000000    0.000000   
25%      1.000000   99.000000   62.000000    0.000000    0.000000   27.300000   
50%      3.000000  117.000000   72.000000   23.000000   32.000000   32.000000   
75%      6.000000  140.000000   80.000000   32.000000  127.500000   36.600000   
max     17.000000  199.000000  122.000000   99.000000  846.000000   67.100000   

            0.627          50           1  
count  767.000000  767.000000  767.000000  
mean     0.471674   33.219035    0.348110  
std      0.331497   11.752296    0.476682  
min      0.078000   21.000000    0.000000  
25%      0.243500   24.000000    0.000000  
50%      0.371000   29.000000    0.000000  
75%      0.625000   41.000000    1.000000  
max      2.420000   81.000000    1.000000

#### 훈련/테스트 데이터셋 분리

In [47]:
from sklearn.model_selection import train_test_split 
X_train, X_test, y_train, y_test = train_test_split(
     X, y, test_size=0.2, random_state=2021
) 

In [48]:
np.unique(y_train, return_counts=True)

(array([0, 1], dtype=int64), array([403, 211], dtype=int64))

1) DecisionTreeClassifier

In [70]:
import warnings
warnings.filterwarnings('ignore')

from sklearn.tree import DecisionTreeClassifier
from sklearn.svm import SVC
from sklearn.model_selection import GridSearchCV

In [71]:
from sklearn.tree import DecisionTreeClassifier
dtc = DecisionTreeClassifier(random_state=2021)
dtc.get_params() 

{'ccp_alpha': 0.0,
 'class_weight': None,
 'criterion': 'gini',
 'max_depth': None,
 'max_features': None,
 'max_leaf_nodes': None,
 'min_impurity_decrease': 0.0,
 'min_impurity_split': None,
 'min_samples_leaf': 1,
 'min_samples_split': 2,
 'min_weight_fraction_leaf': 0.0,
 'random_state': 2021,
 'splitter': 'best'}

In [168]:
params = {
    'max_depth': [2,3,4,5,6],
    'min_samples_split': [2,3,4]
}

In [169]:
grid_dt = GridSearchCV(dtc, param_grid=params, scoring='accuracy', cv=5)
grid_dt.fit(X_train, y_train)
grid_dt.best_params_

{'max_depth': 4, 'min_samples_split': 2}

In [170]:
best_dt = grid_dt.best_estimator_
best_dt.score(X_test, y_test)

0.7467532467532467

2) Support Vector Machine

In [171]:
svc = SVC(random_state=2021)
svc.get_params()

{'C': 1.0,
 'break_ties': False,
 'cache_size': 200,
 'class_weight': None,
 'coef0': 0.0,
 'decision_function_shape': 'ovr',
 'degree': 3,
 'gamma': 'scale',
 'kernel': 'rbf',
 'max_iter': -1,
 'probability': False,
 'random_state': 2021,
 'shrinking': True,
 'tol': 0.001,
 'verbose': False}

In [295]:
params = {'C': [0.001, 0.01, 0,1, 10, 100]}
grid_sv = GridSearchCV(svc, param_grid=params, scoring='accuracy', cv=5)
grid_sv.fit(X_train, y_train)
grid_sv.best_params_

{'C': 10}

In [296]:
best_sv = grid_sv.best_estimator_
best_sv.score(X_test, y_test)

0.7467532467532467

In [290]:
params = {'C': [0.6, 0.7, 0.8]}
grid_sv = GridSearchCV(svc, param_grid=params, scoring='accuracy', cv=5)
grid_sv.fit(X_train, y_train)
grid_sv.best_params_

{'C': 0.6}

In [291]:
best_sv = grid_sv.best_estimator_
best_sv.score(X_test, y_test)

0.7727272727272727

# 정답

In [297]:
import numpy as np
import pandas as pd

데이터 전처리

In [300]:
df = pd.read_csv('pima-indians-diabetes.csv', skiprows=9, header=None)
df.head()

0    1   2   3    4     5      6   7  8
0  6  148  72  35    0  33.6  0.627  50  1
1  1   85  66  29    0  26.6  0.351  31  0
2  8  183  64   0    0  23.3  0.672  32  1
3  1   89  66  23   94  28.1  0.167  21  0
4  0  137  40  35  168  43.1  2.288  33  1

In [302]:
df[1].head()

0    148
1     85
2    183
3     89
4    137
Name: 1, dtype: int64

In [303]:
# 1. Number of times pregnant
# 2. Plasma glucose concentration a 2 hours in an oral glucose tolerance test
# 3. Diastolic blood pressure (mm Hg)
# 4. Triceps skin fold thickness (mm)
# 5. 2-Hour serum insulin (mu U/ml)
# 6. Body mass index (weight in kg/(height in m)^2)
# 7. Diabetes pedigree function
# 8. Age (years)
# 9. Class variable (0 or 1)
df.columns = ['P','G','BP','S','I','BMI','D','Age', 'Class']
df.head()

P    G  BP   S    I   BMI      D  Age  Class
0  6  148  72  35    0  33.6  0.627   50      1
1  1   85  66  29    0  26.6  0.351   31      0
2  8  183  64   0    0  23.3  0.672   32      1
3  1   89  66  23   94  28.1  0.167   21      0
4  0  137  40  35  168  43.1  2.288   33      1

In [304]:
df.index[:5]

RangeIndex(start=0, stop=5, step=1)

In [327]:
# 결측치 데이터가 있는지 확인
df.isna().sum()         # inna() 또는 isnull() 사용하여 확인할 수 있음

P        0
G        0
BP       0
S        0
I        0
BMI      0
D        0
Age      0
Class    0
dtype: int64

In [305]:
X = df.iloc[:, :-1]
X.head()

P    G  BP   S    I   BMI      D  Age
0  6  148  72  35    0  33.6  0.627   50
1  1   85  66  29    0  26.6  0.351   31
2  8  183  64   0    0  23.3  0.672   32
3  1   89  66  23   94  28.1  0.167   21
4  0  137  40  35  168  43.1  2.288   33

In [307]:
X = df.iloc[:, :-1].values
type(X)

numpy.ndarray

In [308]:
X[:5]

array([[6.000e+00, 1.480e+02, 7.200e+01, 3.500e+01, 0.000e+00, 3.360e+01,
        6.270e-01, 5.000e+01],
       [1.000e+00, 8.500e+01, 6.600e+01, 2.900e+01, 0.000e+00, 2.660e+01,
        3.510e-01, 3.100e+01],
       [8.000e+00, 1.830e+02, 6.400e+01, 0.000e+00, 0.000e+00, 2.330e+01,
        6.720e-01, 3.200e+01],
       [1.000e+00, 8.900e+01, 6.600e+01, 2.300e+01, 9.400e+01, 2.810e+01,
        1.670e-01, 2.100e+01],
       [0.000e+00, 1.370e+02, 4.000e+01, 3.500e+01, 1.680e+02, 4.310e+01,
        2.288e+00, 3.300e+01]])

In [344]:
# 여러가지 방법으로 y값을 취할 수 있음
y = df.Class                  # Series
y = df['Class'].values        # Numpy array
y = df.Class.values           # Numpy array
y = df.iloc[:,-1].values      # Numpy array

In [345]:
X.shape, y.shape

((768, 8), (768,))

- 참고사항 : 결측치

In [346]:
df2 = pd.DataFrame(np.arange(25).reshape(5,5), index=list('abcde'), columns=list('vwxyz'))
df2

v   w   x   y   z
a   0   1   2   3   4
b   5   6   7   8   9
c  10  11  12  13  14
d  15  16  17  18  19
e  20  21  22  23  24

In [347]:
# 데이터프레임은 컬럼단위로 동일한 단위값이어야함, 정수를 실수로 바꿈
df2['v']['c'] = np.nan
df2.z['d'] = np.nan
df2

v   w   x   y     z
a   0.0   1   2   3   4.0
b   5.0   6   7   8   9.0
c   NaN  11  12  13  14.0
d  15.0  16  17  18   NaN
e  20.0  21  22  23  24.0

In [348]:
# False = 0, True = 1로 바꿔줌
df2.isna().sum()

v    1
w    0
x    0
y    0
z    1
dtype: int64

In [349]:
# Null값 갯수
df2.isna().sum().sum()

2

- Train/Test dataset으로 분리

In [350]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(
    X, y, stratify=y, test_size=0.2, random_state=2021
)

In [351]:
np.unique(y, return_counts=True)

(array([0, 1], dtype=int64), array([500, 268], dtype=int64))

In [352]:
np.unique(y_train, return_counts=True)

(array([0, 1], dtype=int64), array([400, 214], dtype=int64))

- GridSearchCV, DecisionTreeClassifier

In [353]:
from sklearn.tree import DecisionTreeClassifier
dtc = DecisionTreeClassifier(random_state=2021)
params = {
    'max_depth': [2,3,4,5,6],
    'min_samples_split': [2,3,4]
}

In [354]:
from sklearn.model_selection import GridSearchCV
grid_dt = GridSearchCV(dtc, param_grid=params, scoring='accuracy', cv=5)
grid_dt.fit(X_train, y_train)

GridSearchCV(cv=5, estimator=DecisionTreeClassifier(random_state=2021),
             param_grid={'max_depth': [2, 3, 4, 5, 6],
                         'min_samples_split': [2, 3, 4]},
             scoring='accuracy')

In [355]:
grid_dt.best_params_

{'max_depth': 2, 'min_samples_split': 2}

In [356]:
# 더 나은 결과식
grid_dt.best_estimator_.score(X_test, y_test)

0.7337662337662337

In [357]:
best_dt = grid_dt.best_estimator_
best_dt.score(X_test, y_test)

0.7337662337662337

- 실제 적용

In [358]:
X_test[10], y_test[10]

(array([ 12.   , 100.   ,  84.   ,  33.   , 105.   ,  30.   ,   0.488,
         46.   ]),
 0)

In [361]:
test_data = X_test[10].reshape(1,-1)

In [364]:
# 예측값 predict
pred = best_dt.predict(test_data)
pred

array([0], dtype=int64)

In [367]:
print('양성' if pred[0] == 1 else '음성')       # 3항 연산자(단순한 if문은 한줄로)

음성


In [369]:
# 단순한 if문은 3항 연산자로 쓰는게 좋다(1줄로 씀)
if pred[0] == 1:
    print('양성')
else:
    print('음성')

음성
